server:
  port: 6001

spring:
  application:
    name: mic-productcategory
  datasource:
    url: jdbc:postgresql://localhost:5432/productcategory
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: false