spring:
  application:
    name: mic-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/productcategory
    username: ${POSTGRES_USER:userAuth}
    password: ${POSTGRES_PASSWORD:passAuth}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true